## Here is the link to install ['FAISS'](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md)

In [3]:
import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

[[1.91519454e-01 6.22108757e-01 4.37727749e-01 ... 6.24916732e-01
  4.78093803e-01 1.95675179e-01]
 [3.83317441e-01 5.38736843e-02 4.51648414e-01 ... 1.51395261e-01
  3.35174650e-01 6.57551765e-01]
 [7.53425434e-02 5.50063960e-02 3.23194802e-01 ... 3.44416976e-01
  6.40880406e-01 1.26205325e-01]
 ...
 [1.00811470e+02 5.90245306e-01 7.98893511e-01 ... 3.39859009e-01
  3.01949501e-01 8.53854537e-01]
 [1.00669464e+02 9.16068792e-01 9.55078781e-01 ... 5.95364332e-01
  3.84918079e-02 1.05637990e-01]
 [1.00855637e+02 5.91134131e-01 6.78907931e-01 ... 2.18976989e-01
  6.53015897e-02 2.17538327e-01]]


In [4]:
import faiss
index = faiss.IndexFlatL2(d)
print(index.is_trained)
index.add(xb)
print(index.ntotal)

ModuleNotFoundError: No module named 'faiss'

In [6]:
k = 3                         # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

[[  0 393 363]
 [  1 555 277]
 [  2 304 101]
 [  3 173  18]
 [  4 288 370]]
[[0.        7.1751738 7.20763  ]
 [0.        6.3235645 6.684581 ]
 [0.        5.7964087 6.391736 ]
 [0.        7.2779055 7.5279875]
 [0.        6.7638035 7.2951202]]
[[ 381  207  210]
 [ 526  911  142]
 [ 838  527 1290]
 [ 196  184  164]
 [ 526  377  120]]
[[ 9900 10500  9309]
 [11055 10895 10812]
 [11353 11103 10164]
 [10571 10664 10632]
 [ 9628  9554 10036]]
