## Here is the link to install ['FAISS'](https://github.com/facebookresearch/faiss/blob/main/INSTALL.md)

In [7]:
import numpy as np
d = 64                           # dimension
nb = 100000                      # database size
nq = 10000                       # nb of queries
np.random.seed(1234)             # make reproducible
xb = np.random.random((nb, d)).astype('float32')
xb[:, 0] += np.arange(nb) / 1000.
xq = np.random.random((nq, d)).astype('float32')
xq[:, 0] += np.arange(nq) / 1000.

In [8]:
import faiss
index = faiss.IndexFlatL2(d)
print(index.is_trained)
index.add(xb)
print(index.ntotal)

True
100000


In [9]:
k = 3                         # we want to see 4 nearest neighbors
D, I = index.search(xb[:5], k) # sanity check
print(I)
print(D)
D, I = index.search(xq, k)     # actual search
print(I[:5])                   # neighbors of the 5 first queries
print(I[-5:])                  # neighbors of the 5 last queries

[[  0 393 363]
 [  1 555 277]
 [  2 304 101]
 [  3 173  18]
 [  4 288 370]]
[[0.        7.1751738 7.20763  ]
 [0.        6.3235645 6.684581 ]
 [0.        5.7964087 6.391736 ]
 [0.        7.2779055 7.5279875]
 [0.        6.7638035 7.2951202]]
[[ 381  207  210]
 [ 526  911  142]
 [ 838  527 1290]
 [ 196  184  164]
 [ 526  377  120]]
[[ 9900 10500  9309]
 [11055 10895 10812]
 [11353 11103 10164]
 [10571 10664 10632]
 [ 9628  9554 10036]]
